media_list = {
    "txt":"text/txt",
    "html":"text/html",
    "css":"text/css",
    "js":"text/js",
    "jpg":"image/jpg",
    "JPG":"image/JPG",    
    "jpeg":"image/jpeg",
    "JPEG":"image/JPEG",
    "png":"image/png",
    "PNG":"image/PNG",
    "gif":"image/gif",
    "ico":"image/ico",
    "mp4":"video/mp4",
    "mp3":"audio/mp3",
    "otf":"application/x-font-otf",
    "woff":"application/x-font-woff",
    "ttf":"application/x-font-ttf"
    }
