media_list = {
    "txt":"text",
    "html":"text",
    "css":"text",
    "js":"text",
    "jpg":"image",
    "JPG":"image",    
    "jpeg":"image",
    "JPEG":"image",
    "png":"image",
    "PNG":"image",
    "gif":"image",
    "ico":"image",
    "mp4":"video",
    "mp3":"audio",
    "otf":"application/x-font-otf",
    "woff":"application/x-font-woff",
    "ttf":"application/x-font-ttf"
    }
